### ISSUE TITLE
Support union/union all cases

### ISSUE THREAD

**Issue by stanislav-poliakov** [Dzoukr/Dapper.FSharp#101]
It will be great have possibility to use it

```
for p in personTable do
where (p.Position > 5)
unionAll
for p in personTable do
p.Position < 10)
```

```
for p in personTable do
where (p.Position > 5)
distinctUnion //or just `union`
for p in personTable do
p.Position < 10)
```

**Comment by Dzoukr** [comment]
Currently, there is no support for having two selects in one query 🤔 ... but it should be possible in theory...

**Comment by JordanMarr** [comment]
It might require something like this:

```F#
let positionLt10 = 
    select { 
        for p in personTable do
        where (p.Position < 10)
    }

select {
    for p in personTable do
    where (p.Position > 5)
    unionAll positionLt10
}
 |> conn.SelectAsync<Person>
```

OTOH, that's kind of clunky, so I'm inclined to think that this is one of those "write a manual query" situations.

**Comment by Dzoukr** [comment]
> OTOH, that's kind of clunky, so I'm inclined to think that this is one of those "write a manual query" situations.

Same here. Let's keep the API nice and clean.
