### ISSUE TITLE
Is there a query that implements something like `QueryFirst`, `QueryFirstOrDefault`?

### ISSUE THREAD

**Issue by vitash** [Dzoukr/Dapper.FSharp#103]
The following code queries the first data by id:
``` f#
let findById id = task {
    let! data =
        select {
            for u in Tbl do
            where (u.id = id)
            take 1
        } |> conn.SelectAsync<'a>
    return data |> Seq.tryHead
}
```
It would be simpler to have something like `QueryFirstOrDefault` and want the return value to be of `option` type.

**Comment by Dzoukr** [comment]
I think it's rather about personal taste so I'll keep that for custom project-specific wrappers.

**Comment by vitash** [comment]
Got it. Thanks.
