### ISSUE TITLE
SQLite OptionTypes missing String option converter

### ISSUE THREAD

**Issue by ghandy-dev** [Dzoukr/Dapper.FSharp#106]
I encounter an error when trying to write a string option (that is None) to a SQLite database

```The member channel of type Microsoft.FSharp.Core.FSharpOption`1[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]] cannot be used as a parameter value```

I believe this would be the required change (likely not a breaking change):

```F#
[<RequireQualifiedAccess>]
module Dapper.FSharp.SQLite.OptionTypes

// ...
type SqliteOptionStringHandler()         = inherit OptionTypeHandlerWithConverter<String>(Convert.ToString)

let register() =
// ...
    SqlMapper.AddTypeHandler(SqliteOptionStringHandler())
```

**Comment by Dzoukr** [comment]
I see you are working on fix in your fork. When you have it done + have test for it, please send a PR 🙏

**Comment by ghandy-dev** [comment]
I've opened a draft pull request for the moment as I came across an issue when writing tests for this. 

After much confusion as to why tests I wrote that should have been failing were actually passing I eventually realised that some of the other vendor register methods must be called before the SQLite tests ran, and they also register a string option handler. So in a sense I am not really testing the change since the tests aren't isolated in a way that it just tests SQLite, while at the same time it is confirming existing functionality - which is all I've added anyway!

I have however confirmed this fixes the issue I had. If you're fine with how it currently is I can update the draft ready for review.

**Comment by radekm** [comment]
Hmm. Interesting. I'm using `Dapper.FSharp` with tables containing many `string option` columns with both `None` and `Some` values and it is working and it was working. I'm wondering why it's not working for you and why it is working for me?

The only difference I see is that I have `[<CLIMutable>]` attribute on my records.

**Comment by ghandy-dev** [comment]
@radekm, yes I noticed that adding that worked as a work-around. 

The F# docs state regarding `[<CLIMutable>]`:

> Adding this attribute to a record type causes it to be compiled to a CLI representation with a default constructor with property getters and setters. 

So it likely compiles to a compatible C# object, and the F# record's fields that are `Option` types get mapped to Nullable properties. It would then return `null` instead of `None`, and Dapper can already map C# nullable value/object types to a null DB value.

**Comment by ghandy-dev** [comment]
@radekm, after some further thought it was partially my use case, where I wasn't using the built Dapper.FSharp `insert`. I had a slightly more complex query which I was executing against Dapper methods. 

Much simpler, but I had something like this.

```F#
type A = {
    fieldA: string
    fieldB: string option
}

let addA (record: A) =
    task {
        let sql = """
            INSERT INTO TableA (field_a, field_b)
            VALUES (@fieldA, @fieldB);"""
        
        let! _ = connection.ExecuteAsync(sql, record)

        return ()
    }
```

So I'd be making the guess that some of the glue was missing that makes it work in Dapper.FSharp? because it works fine using the Dapper.FSharp `insert` statement on 4.8.0.

But I also did notice that using a `select` that it didn't work. I would get an exception such as the following:
`One or more errors occurred. (A parameterless default constructor or one matching signature (System.String fieldA, System.String fieldB) is required for FSI_0086+B materialization)`

Perhaps the parameterless constructor, and setters you get with a [<CLIMutable>] attribute get around that issue and it's able to map the columns, or maybe it's a more expected path for code to take.
