### ISSUE TITLE
Table names with reserved names throw exception (SQL Server)

### ISSUE THREAD

**Issue by ssiltanen** [Dzoukr/Dapper.FSharp#11]
How to repro:
- Have a table named eg. Group
- select { table "Group" }
- execute query

How to mitigate:
- Add [ ] around table name in generated SQL eg. Select .... FROM [Group]
- User is able to mitigate this by themselves only if there is no joins or where in the query by adding [] by hand to table definition in select query.

This is also an issue in other queries other than just select.

Not sure if this is an issue in other database engines.

**Comment by Dzoukr** [comment]
Hello @ssiltanen, thanks for finding out. MSSQ is already fixed, working on MySQL & Postgres. Will release fix soon.

**Comment by Dzoukr** [comment]
Fixed in `v1.12.1`
