### ISSUE TITLE
Please include sources in Nuget package

### ISSUE THREAD

**Issue by randrag** [Dzoukr/Dapper.FSharp#18]
Hi Roman, thank you for the great library.

On my machine, using Rider and Nuget vir Paket, I can't see the F# source code (I get decompiled C#). With some other packages, like FsToolkit.Errorhandling, I can see the F# source. 

Apparently this is something to do with the way it was packaged - I found this page describing source link for Nuget packages: https://devblogs.microsoft.com/nuget/introducing-source-code-link-for-nuget-packages/

It would be great if you could include a link to the source when you package up the next.

Thanks again for the great library.

Roland

**Comment by Dzoukr** [comment]
Hi Roland,
thanks a lot for using it (and liking it) 😄 

I'll try to look at it, but if you could send PR, that would help.

**Comment by randrag** [comment]
Hi Roman, it will be good for me to learn how Nuget packaging works (without pushing to Nuget.org) - I will have a look and send a PR if I get it working.

**Comment by Dzoukr** [comment]
To test it, it should be rather easy. Just clone the repo, run `dotnet tool restore` and then `dotnet build -t pack` and you should get the new package in bin folder.
