### ISSUE TITLE
Synchronous/False Synchronous Example

### ISSUE THREAD

**Issue by dredgy** [Dzoukr/Dapper.FSharp#23]
Not really an issue, just would like a good syntactical example of how to use these queries in a synchronous or false synchronous (await) way. I.e - I have a select{} statement and I want to get the results collection in the same function. I am new to .NET and F# so it’s not always easy to follow these things or even to know what to learn in specific cases like this! My app is very synchronous and linear - nothing can happen until the query is executed in most cases.

**Comment by Dzoukr** [comment]
Hi @dredgy, I understand ... and welcome to F# community! 🚀 

I would still strongly suggest to get used to async style as soon as possible, because it's the _default_ way of handling IO in nearly any language these days. But if you really need synchronous example, I can give you one:

```fsharp
insert {
    table "Persons"
    value {| Name = "Roman"; Surname = "Provaznik" |}
} |> conn.Insert // <-- note here, no Insert instead of InsertAsync
```

Also check the examples in test project https://github.com/Dzoukr/Dapper.FSharp/tree/master/tests/Dapper.FSharp.Tests

**Comment by dredgy** [comment]
Thanks! That’s interesting, my connection doesn’t have that as an option, will investigate further! Though I am perfectly happy to use async, just in other languages I can use it in a way that simulate sync without taking up too many lines and haven’t figured out how to do that in F# yet, will read the tests now. Thanks for the help, I really appreciate the library!

**Comment by Dzoukr** [comment]
Oh, my fault! You are absolutely right - I didn't implement sync versions (probably on purpose to force people to use - correct - async version) 😄

**Comment by Dzoukr** [comment]
But yeah... async in F# is really easy! You can use one of the great libraries like https://github.com/rspeele/TaskBuilder.fs to have `task` computation expression available, where you can just use `let!` instead of `let` and it works.

Or you can do it "manually":

```fsharp
insert {
    table "Persons"
    value {| Name = "Roman"; Surname = "Provaznik" |}
} 
|> conn.InsertAsync 
|> Async.AwaitTask 
|> Async.RunSynchronously
```

**Comment by dredgy** [comment]
Thanks!
`|> Async.AwaitTask 
|> Async.RunSynchronously` is what I needed. Appreciate all the help!
