### ISSUE TITLE
Update table with dynamic column name?

### ISSUE THREAD

**Issue by dredgy** [Dzoukr/Dapper.FSharp#25]
Not exactly a big deal but wanting to do a simple update column function

eg `let updateColumn key column value`

Looking at the partial update expression, I’d want something  similar to this:

```
let updateColumn key column value  =
    update {
        table "Persons"
        set {| column = value |}
        where (eq "person-id" key)
    } |> conn.UpdateAsync
```

Is this possible? Computation expressions are very confusing to me!

**Comment by Dzoukr** [comment]
Good day to you too! 😄 

If you need this kind of flexibility, where you don't know column name or value upfront, fallback to plain Dapper then. Column names are generated via reflection from anonymous/named records and if you take away this, there's no need to use anything else than plain Dapper like:

```fsharp
let updateColumn key column value =
    let sql = "UPDATE Persons SET @col = @val WHERE person-id = @key"
    let pars = [("col", box column); ("val", box value); ("key", box key)]
    connection.ExecuteAsync(sql, pars)
```

**Comment by dredgy** [comment]
Thanks a lot! That’s what I’m currently using, just was converting all my functions from plain dapper to your library where I could and this was the only place I couldn’t! So was more curious about passing arguments into expressions as it seemed a good thing to be able to learn.

Loving the library so far, is so easy to use!


________________________________
