### ISSUE TITLE
New comparison operators

### ISSUE THREAD

**Issue by JordanMarr** [Dzoukr/Dapper.FSharp#38]
There are a handful of new comparison operators that I implemented in SqlHydra that you may be interested in:

isIn or |=|
isNotIn or |<>|
like or =%
notLike or <>%

(They are the same operators used in SqlProvider, so they should be familiar to some people already).

**Comment by Dzoukr** [comment]
I think if we put them in a separated module *.Operators, that would be a great addition!

**Comment by Dzoukr** [comment]
Released as `v2.3.0`
