### ISSUE TITLE
Left Join on Multiple Columns

### ISSUE THREAD

**Issue by tskj** [Dzoukr/Dapper.FSharp#43]
Is it possible to get [this api](https://github.com/Dzoukr/Dapper.FSharp/issues/36) for `leftJoin` as well?

**Comment by Dzoukr** [comment]
You mean this? https://github.com/Dzoukr/Dapper.FSharp#joins

**Comment by tskj** [comment]
Sorry I should have been more clear maybe - or perhaps I didn't see it in the documentation. I want multiple column joins on jeftJoin, exactly the same as the new api for innerJoins!

```
table "A"
leftJoin "B" [ "A.x", "A.y"; "B.x", "B.y" ]
```

**Comment by JordanMarr** [comment]
That should be pretty easy to port over, right @TerenceHinrichsen?

**Comment by TerenceHinrichsen** [comment]
Most definitely, should be able to get it done fairly quickly.

**Comment by tskj** [comment]
Wow thanks, that's brilliant! When can I expect this to be available in a release?

**Comment by Dzoukr** [comment]
PR just released as `v2.4.0`, thanks @TerenceHinrichsen again for amazing work!

**Comment by tskj** [comment]
This worked brilliantly, exactly what I needed, thank you so much for the quick execution!
