### ISSUE TITLE
Make README code samples valid (Add requirement for `[<CLIMutable>]` attribute to docs)

### ISSUE THREAD

**Issue by greggyb** [Dzoukr/Dapper.FSharp#67]
It seems based on guides and posts elsewhere that F# record types must be annotated with `[<CLIMutable>]` to interoperate with Dapper queries. In my own experience, following the code samples in the README leads to exceptions that are not readily resolvable without some significant further digging.

It would be helpful for the samples in the README to be valid and working code.

**Comment by Dzoukr** [comment]
Hi, `[CLIMutable]` is not required for this library - see the examples in Tests folder.
