### ISSUE TITLE
Add support for SQLite (Microsoft.Data.SQLite)

### ISSUE THREAD

**Issue by prosconi** [Dzoukr/Dapper.FSharp#73]
Since #71 was implemented and everything is separated out to their own namespace, I think it makes sense to add a ``Dapper.FSharp.SQLite`` namespace with a SQLite specific implementation.

The new implementation can support ``INSERT OR REPLACE`` (see: https://www.sqlite.org/lang_conflict.html)

**Example implementation of INSERT OR REPLACE**

```fsharp
let! conflictCount = 
    insert {
        orReplace
        into personsView
        values modified
    }
    |> conn.InsertAsync
```

Since SQLite does not support most data types, ``TypeHandlers`` should be created (see: https://learn.microsoft.com/en-us/dotnet/standard/data/sqlite/types)

I already have an implementation working locally.

**Comment by Dzoukr** [comment]
Cool! Free feel to send a PR.

**Comment by prosconi** [comment]
PR submitted

**Comment by Dzoukr** [comment]
Perfect, will have a look!

**Comment by Dzoukr** [comment]
Merged, tested, deployed - thanks for the great work!
