### ISSUE TITLE
Sqlite and multiple type registration

### ISSUE THREAD

**Issue by kaaja-h** [Dzoukr/Dapper.FSharp#78]
When using sqlite you have to register types using this way
```
OptionTypes.register ()
Dapper.FSharp.SQLite.TypeHandlers.addSQLiteTypeHandlers ()
```
but you register some type converter more than once.
For example TimeSpan option
I found that dapper sometime select convertor from OptionTypes.register() and sometime from addSQLiteTypeHandlers().
For example for TimeSpan it is problem, because convertor from OptionTypes.register() don't use TimeSpan.Parse and throws exception.

**Comment by Dzoukr** [comment]
Hi @kaaja-h, hmmm... I've never thought about it. Probably in the next version, I would have to add Type registration on the dbvendor-type level. Will look at it.

**Comment by Dzoukr** [comment]
Workaround, for now, is to create your own handlers function and not call the Dapper.FSharp ones

**Comment by Dzoukr** [comment]
Published in the new version - now there should be one registration per db vendor
