### ISSUE TITLE
namespace 'LinqBuilders' is not defined

### ISSUE THREAD

**Issue by diegopego** [Dzoukr/Dapper.FSharp#81]
Hi! I got this message
error FS0039: The namespace 'LinqBuilders' is not defined

Program.fs:
`open Dapper.FSharp.LinqBuilders`

paket.lock
```
STORAGE: NONE
RESTRICTION: == net7.0
NUGET
  remote: https://api.nuget.org/v3/index.json
    Dapper (2.0.123)
    Dapper.FSharp (4.3)
      Dapper (>= 2.0.123)
      FSharp.Core (>= 6.0.7)
    FSharp.Core (7.0)
    Microsoft.Extensions.Logging.Abstractions (7.0)
    Microsoft.NETCore.Platforms (7.0)
    Microsoft.NETCore.Targets (5.0)
    Npgsql (7.0.1)
      Microsoft.Extensions.Logging.Abstractions (>= 6.0)
    SqlHydra.Query (1.1.1)
      FSharp.Core (>= 5.0.2)
      SqlKata (>= 2.4)
```

**Comment by Dzoukr** [comment]
Hi, did you just update from some old version?

**Comment by diegopego** [comment]
No, It is a fresh new project.
To be sure. I created a new empty project:

```
OS: Windows 11

dotnet nuget Install-Package Dapper.FSharp
dotnet add package Dapper.FSharp

dotnet --list-sdks
5.0.415 [C:\Program Files\dotnet\sdk]
6.0.405 [C:\Program Files\dotnet\sdk]
7.0.102 [C:\Program Files\dotnet\sdk]
```

I got the same error.

![image](https://user-images.githubusercontent.com/5631904/216966959-dcb5a05c-4794-4525-9a63-e7818dc95c41.png)

![image](https://user-images.githubusercontent.com/5631904/216966772-b448166f-33ba-4af8-9c5d-2be5e4b3a100.png)

**Comment by Dzoukr** [comment]
And why do you need them? 🤔

**Comment by diegopego** [comment]
I'm testing SqlHydra and Dapper example https://github.com/JordanMarr/SqlHydra/wiki/DataReaders#dapper

**Comment by Dzoukr** [comment]
I seeeeeeee. 😄 Yup, it's an old example - please just use what's in this repo README and it should work ok.

**Comment by JordanMarr** [comment]
Yup, just delete the `open Dapper.FSharp.LinqBuilders` line and you should be good to go!
(The LinqBuilders were moved into the main `Dapper.FSharp` namespace.)

**Comment by diegopego** [comment]
Thank you again!
I'm an FSharp beginner. I'm finding it hard to take off with the README and current tests, would you mind if I try to create a beginners HOWTO and make a PR?
Also, may I please ping you if I'm in deep trouble while doing it?

**Comment by Dzoukr** [comment]
Welcome to the best community EVER, bro! 🎊 🎆 🥳 

Sure, feel free to send any improvement! 👍
