### ISSUE TITLE
Not Implemented Exception While Using SRTP

### ISSUE THREAD

**Issue by 1eyewonder** [Dzoukr/Dapper.FSharp#90]
**Issue**
Calling code similar to below will result in a Not Implemented Exception. Area of code is found here for the 'isIn' function https://github.com/Dzoukr/Dapper.FSharp/blob/master/src/Dapper.FSharp/MSSQL/LinqExpressionVisitors.fs#L218

**Use Case**
I have a quite a few similar queries where I need to check for existence in various tables and other minute validations. If I am thinking about this correctly, I think adding support for SRTP would provide benefit in being able to create re-usable queries so I don't have to create a new query for each table.

```fsharp
#r "nuget: Dapper.FSharp"
open Dapper.FSharp
open Dapper.FSharp.MSSQL
open System.Data

[<CLIMutable>]
type Person = 
    { 
        Id : int 
    }

[<CLIMutable>]
type Dog = 
    { 
        Id : int 
    }

let people = table'<Person> "People"
let dogs = table'<Dog> "Dogs"

let inline getIds<'T 
    when 'T: (member Id : int)> 
    (ids : int list) 
    (querySource : QuerySource<'T>) 
    (conn : IDbConnection) 
    = async {
    // This is required in order to use SRTP w/ the query builder
    let getId (item : 'T) = item.Id
    
    let query = select {
        for row in querySource do
            where (isIn (getId row) ids)
    }

    return! conn.SelectAsync<'T>(query) |> Async.AwaitTask
}
```

**Comment by JordanMarr** [comment]
I'm pretty sure that only the `SelectAsync<'T>` method is what reflects the columns to pull.
So rather than using an SRTP, I think you could probably just create a single partial object that has only the `Id` field for querying, and then pass in a generic argument of the full table class that contains all the properties you actually want to load.

```F#
[<CLIMutable>]
type IdColumn = { Id: int  }

let getIds<'T> (ids: int list) (querySource: QuerySource<IdColumn>) (conn: IDbConnection) = 
  async {
    let query = 
      select {
          for row in querySource do
          where (isIn row.Id ids)
      }

    return! conn.SelectAsync<'T>(query) |> Async.AwaitTask
  }
```

```F#
let querySource = table'<IdColumn> "Dogs"
let! dogs = getIds<Dog> [1;2;3] querySource conn
```

**Comment by 1eyewonder** [comment]
Wow, I feel stupid for not thinking of this 🤦‍♂️. Thank you, this makes sense!

**Comment by 1eyewonder** [comment]
So more of a philosophical question now. Is the SRTP support still a valid request/issue for this repo? While the 'ID' use case is very straight forward, does it make sense to suggest this route for other alternatives? Silly examples below.

```fsharp
[<CLIMutable>]
type IdColumn = { Id: int  }

[<CLIMutable>]
type IdAndBirthdateColumn = { Id: int; Foo1: int;  }

[<CLIMutable>]
type IdFoo1Foo2Column = { Id: int; Foo1: int; Foo2; int  }
```

So while code quantity wouldn't really differ between the DTO and the SRTP routes, the pain of naming is placed on users(devs). The STRP would just allow users to focus on what is needed for the generic queries rather than come up with a DTO for each use case. (Granted I'm not sure how often users come across this since I haven't really dealt with it until the other day). I'm sure it may just end up being diminishing returns trying to pursue this route, but I figured I'd ask the question while the issue was still open. If you think it's not worth pursuing, I can go ahead and close the issue.

**Comment by JordanMarr** [comment]
I think using an anonymous record would be the better play:

```F#
let queryByIds<'T> (ids: int list) tableName (conn: IDbConnection) = 
  async {
    let query = 
      select {
          for row in table'<{| Id: int |}> tableName do
          where (isIn row.Id ids)
      }

    return! conn.SelectAsync<'T>(query) |> Async.AwaitTask
  }
```

```F#
let! dogs = queryByIds<Dog> [1;2;3] "Dogs" conn
```

**Comment by 1eyewonder** [comment]
Yep, that makes sense. Thank you so much for your help!
